# Generated by Django 2.1.5 on 2019-01-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0002_auto_20181227_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='KerasSinglePlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keras_model', models.FileField(editable=False, upload_to='keras_models')),
                ('player', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedOnGame',
            fields=[
                ('id_in_model', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Game')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedOnPlayer',
            fields=[
                ('id_in_model', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Player')),
            ],
        ),
    ]
