# Generated by Django 2.1.5 on 2019-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerassingleplayermodel',
            name='epoch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kerassingleplayermodel',
            name='loss',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kerassingleplayermodel',
            name='output_mean_absolute_error',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kerassingleplayermodel',
            name='val_loss',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kerassingleplayermodel',
            name='val_output_mean_absolute_error',
            field=models.FloatField(default=None, null=True),
        ),
    ]
