# Generated by Django 2.1.5 on 2019-01-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20190126_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kerassingleplayermodel',
            old_name='keras_model',
            new_name='keras_model_file',
        ),
    ]
