# Generated by Django 2.1.5 on 2019-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20190128_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerassingleplayermodel',
            name='model_indice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
