# Generated by Django 2.1.5 on 2019-01-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_kerassingleplayermodel_model_indice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerassingleplayermodel',
            name='model_indice',
        ),
    ]
