# Generated by Django 2.1.5 on 2019-02-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_kerassingleplayermodel_model_indice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerassingleplayermodel',
            name='output_mean_absolute_error',
        ),
        migrations.RemoveField(
            model_name='kerassingleplayermodel',
            name='val_output_mean_absolute_error',
        ),
    ]
