# Generated by Django 2.1.5 on 2019-02-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20190207_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerassingleplayermodel',
            name='player',
        ),
        migrations.DeleteModel(
            name='KerasSinglePlayerModel',
        ),
    ]
