# Generated by Django 2.1.5 on 2019-02-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_game_ratings_count'),
        ('training', '0007_auto_20190207_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='KerasSinglePlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('keras_model_file', models.FileField(editable=False, upload_to='keras_models')),
                ('loss', models.FloatField()),
                ('val_loss', models.FloatField()),
                ('player', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Player')),
            ],
        ),
    ]
