version: '3'

services:
  psql:
    image: "postgres:11-alpine"
    restart: always
    volumes:
      - './docker/psql/data.vlm:/var/lib/postgresql/data'
      - './docker/psql/scripts/init-db.sh:/init-db.sh'
    environment:
      - POSTGRES_DB=${PSQL_DB_NAME}
      - POSTGRES_USER=${PSQL_DB_USER}
      - POSTGRES_PASSWORD=${PSQL_DB_PASS}
    ports:
      - ${EXPOSE_DB}:5432

  app:
    build:
      dockerfile: './docker/app/Dockerfile'
      context: '.'
    env_file:
      - app.env
    ports:
      - ${EXPOSE_APP}:8000
    depends_on:
      - psql

  redis:
    image: "redis:5-alpine"
    restart: always
    ports:
      - ${EXPOSE_REDIS}:6739
    depends_on:
      - app
