version: '2.4'

services:
  app:
    build:
      dockerfile: './docker/app/Dockerfile'
      context: '.'
    command: ["start-gunicorn.sh"]
    image: &app app
    env_file:
      - .env
    runtime: nvidia
    networks:
      - celery-net
      - database-net
    volumes:
      - './docker/app/data/keras_models:/var/lib/keras_models'
      - './app:/app'
    ports:
      - ${EXPOSE_APP}:8000
    depends_on:
      - celery
      - psql

  celery:
    image: *app
    command: ["celery", "worker", "--app=game_recommendations", "--loglevel=INFO"]
    env_file:
      - .env
    runtime: nvidia
    networks:
      - celery-net
      - database-net
    volumes:
      - './docker/app/data/keras_models:/var/lib/keras_models'
      - './app:/app'
    depends_on:
      - celery-broker

  psql:
    image: "postgres:11-alpine"
    networks:
      - database-net
    volumes:
      - './docker/psql/data.vlm:/var/lib/postgresql/data'
      - './docker/psql/scripts/init-db.sh:/init-db.sh'
    environment:
      - POSTGRES_DB=${PSQL_DB_NAME}
      - POSTGRES_USER=${PSQL_DB_USER}
      - POSTGRES_PASSWORD=${PSQL_DB_PASS}
    ports:
      - ${EXPOSE_DB}:5432

  celery-broker:
    image: "rabbitmq:3.7-alpine"
    volumes:
      - './docker/celery-broker/data.vlm:/var/lib/rabbitmq'
    networks:
      - celery-net
    ports:
      - ${EXPOSE_RABBITMQ}:5672

networks:
  celery-net:
  database-net:
