#!/bin/sh
set -e

su -- postgres -c \
	psql -v ON_ERROR_STOP=1 --username "$PSQL_DB_USER" --dbname "$PSQL_DB_NAME" \
	<<-EOSQL
		CREATE USER $GAMES_REC_DB_USER PASSWORD '$GAMES_REC_DB_PASS';
		CREATE DATABASE $GAMES_REC_DB_NAME;
		GRANT ALL PRIVILEGES ON $GAMES_REC_DB_NAME TO $GAMES_REC_DB_USER;
	EOSQL
