# Generated by Django 2.1.4 on 2018-12-18 03:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('min_players', models.IntegerField(default=1)),
                ('max_players', models.IntegerField(default=1)),
                ('min_playtime', models.IntegerField(default=30)),
                ('max_playtime', models.IntegerField(default=60)),
                ('weight', models.FloatField(default=3.0)),
                ('dump', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_username', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=8.7)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Player')),
            ],
        ),
    ]
