# Generated by Django 2.1.5 on 2019-01-27 21:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20190121_2212'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('unplayed_games', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(through='ratings.Rating', to='ratings.Game'),
        ),
    ]
