# Generated by Django 2.1.5 on 2019-01-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20190127_2201'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
    ]
