# Generated by Django 2.1.5 on 2019-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20190128_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='standalone',
            field=models.BooleanField(default=False),
        ),
    ]
