# Generated by Django 2.1.5 on 2019-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20190205_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ratings_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
